export const GET_MOVIES = 'GET_MOVIES'
export const GET_USER = 'GET_USER'
export const LOGOUT_USER = 'LOGOUT_USER'
export const CREATE_MOVIE = 'CREATE_MOVIE'
export const SEARCH_MOVIE = 'SEARCH_MOVIE'
